version: '3.8'

services:
  python-service:
    build:
      context: ./python-service
    ports:
      - "5000:5000"
    depends_on:
      - redis
  go-service:
    build:
      context: ./go-service
    ports:
      - "8080:8080"
  node-service:
    build:
      context: ./node-service
    ports:
      - "3000:3000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
